# Generated by Django 5.1 on 2024-08-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='times_completed',
            field=models.IntegerField(default=0),
        ),
    ]
