# Generated by Django 5.1 on 2024-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_times_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(default='Not Completed', max_length=64),
        ),
    ]
