# Generated by Django 5.1 on 2024-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_completed_habit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(default='Habit being formed', max_length=64),
        ),
    ]
