# Generated by Django 5.1 on 2024-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_private_alter_habit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_marked_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
